### ISSUE TITLE
[azure china] Azure key vault plugin not able to authenticate with Service Principal

### ISSUE THREAD

**Issue by tucha1992** [jenkinsci/azure-keyvault-plugin#116]
Hello,

I have configured Azure key vault plugin but when I'm adding key vault url and selecting Azure Service Pricipal Credential then it is giving below error:

AADSTS90002: Tenant 'e6bea6bd-74a5-498e-92c9-5b0ddd5bd6f1' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant.
Trace ID: cabaeeb9-70cd-4a4a-bb5b-298ddcda1600
Correlation ID: 144bfe22-ea66-4be5-8796-099ac43a2fda
Timestamp: 2022-07-19 08:53:15Z

I have checked login using service principal from azure cli and it is working fine. Only in this part is it failing. I have checked adding keyvault in Europe region it is working fine. Issue is happening when I'm using Azure China keyvault and service principal.

**Comment by timja** [comment]
As I'm unable to test in Azure China I do not plan to work on this, contributions are welcome though
