### ISSUE TITLE
Support getting jenkins.azure-keyvault.sp.client_secret value from file

### ISSUE THREAD

**Issue by ajddsolidaris** [jenkinsci/azure-keyvault-plugin#134]
### What feature do you want to see added?

Currently, when setting up the plugin via system properties, all properties are readable by any system users by looking at the processes (e.g. with the `ps` command). This is especially an issue for the `-Djenkins.azure-keyvault.sp.client_secret` property.

Ideally, we should have an additional property to give the path to a file that contains the `client_secret` value (like `-Djenkins.azure-keyvault.sp.client_secret_file`). The Jenkins process would open the file and load the secret value from it. The access to this file could easily be restricted and that would lower the risks of leaks.

**Comment by timja** [comment]
makes sense I would highly recommend using a managed identity if you can anyway.

**Comment by ajddsolidaris** [comment]
Indeed, that would be a nice solution if my Jenkins instance was hosted on Azure.

**Comment by CzapBran** [comment]
@timja @ajddsolidaris I created a PR attempting to add support for secret files instead
