### ISSUE TITLE
Plugin doesn't work over private network with Private Endpoints enabled

### ISSUE THREAD

**Issue by Masahigo** [jenkinsci/azure-keyvault-plugin#165]
### Jenkins and plugins versions report

<details>
  <summary>Azure Key Vault with Private Endpoint and public access disabled</summary>

  
  ```text
// Scripted pipeline
def Azure_Credentials = 'azure-service-principal-credential-id'
def Key_Vaul_Url = 'https://mykeyvault.vault.azure.net'
def secrets = [
                [ secretType: 'Secret', name: 'secret-in-azure-keyvault', envVariable: 'MY_SECRET' ]
]

pipeline {
  stage('Read from Key Vault') {
    steps {
       script {
         withAzureKeyvault(
           azureKeyVaultSecrets: secrets,
           keyVaultURLOverride: Key_Vaul_Url,
           credentialIDOverride: Azure_Credentials) {
             echo 'My secret: $MY_SECRET'
           }               
       }
    }
  }
}

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Configure Azure Service Principal credentials to Jenkins credential store
2. Run the pipeline

### Expected Results

The pipeline should be able to read the secret from Azure Key Vault.

### Actual Results

Status code 403, "{"error":{"code":"Forbidden","message":"Public network access is disabled and request is not from a trusted service nor via an approved private link.\r\nCaller:...;location=westeurope","innererror":{"code":"ForbiddenByConnection"}}}"

### Anything else?

I have tested and confirmed that using Azure CLI (2.46.0) from the pipeline it's able to read the secret from Azure Key Vault

```groovy
withCredentials([azureServicePrincipal(credentialsId: Azure_Credentials)]) {
                        sh 'az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID'
                        sh 'az keyvault secret show --name secret-in-azure-keyvault --vault-name mykeyvault.vault.azure.net'
}
```

When inspecting the AuditEvents from Azure Key Vault I can see that the request made by this plugin (client info: azsdk-java-azure-security-keyvault-secrets/4.4.3 (11.0.16.1; Linux; 5.4.0-120-generic) is routed over public network. The same does not happen with Azure CLI (client info: python/3.8.10 (Linux-5.4.0-120-generic-x86_64-with-glibc2.29) msrest/0.7.1 msrest_azure/0.6.4 azure-keyvault/7.0 Azure-SDK-For-Python).

This is probably a DNS issue. _It's if this plugin does not respect the DNS settings of the Jenkins host._ Instead it uses some default DNS server from public internet which leads to this.

**Comment by timja** [comment]
> It's if this plugin does not respect the DNS settings of the Jenkins host.

It won't be doing that.

Is your `sh` step using Azure CLI running on a Jenkins controller or an agent?
Possibly your agent has access but not the controller?

**Comment by Masahigo** [comment]
> > It's if this plugin does not respect the DNS settings of the Jenkins host.
> 
> It won't be doing that.
> 
> Is your `sh` step using Azure CLI running on a Jenkins controller or an agent? Possibly your agent has access but not the controller?

Hmm.. we have very little control over the Jenkins controller as the whole installation is managed by a third party but the agent definitely respects the DNS setting as it works like it should via Azure CLI.

**Comment by Masahigo** [comment]
Yes, now after checking the documentation on this Jenkins setup it seems indeed so that the Jenkins controller is not connected to the VPN tunnel directly. @timja Any suggestions on how to tackle this?

**Comment by timja** [comment]
The model of the plugin is that the Controller accesses the secrets not agents.

If you want to access it and block public access then you need to give your Jenkins access to that VPN tunnel
