### ISSUE TITLE
Add support for passphrase to be included in private SSH key option

### ISSUE THREAD

**Issue by CzapBran** [jenkinsci/azure-keyvault-plugin#170]
### What feature do you want to see added?

Our private SSH keys are always paired with a passphrase.  As far as I can see, there is no support in the sshUserPrivateKey option when setting tags in the KeyVault.

**Comment by CzapBran** [comment]
I'm working on this solution as well.  My proposed change is:

We include a new optional tag for a passphrase **ID**.  Obviously you wouldn't want to put the passphrase as plaintext in the tag, so this would be an ID (and should be stated as such).  This ID will be the name of another secret in the KV that contains the actual passphrase.

Again, currently working on this solution.

**Comment by timja** [comment]
sounds reasonable if you can get that working 👍.

_Somewhat questionable_ if the passphrase is of any use in your usecase given you are storing the key and passphrase basically next to each other.

**Comment by CzapBran** [comment]
Can you explain your meaning? Not quite sure I understand :)

In Jenkins, when setting a private SSH key, it is usually accompanied by a passphrase.  Obviously we can just fetch both values as is from the KeyVault and set something up in a pipeline, but if we want to interact with the Credentials Binding plugin using tags (like setting a usernamePassword cred through tags), there isn't support for including a passphrase.  

Or maybe I'm completely wrong, would be happy to hear so otherwise 😆 

Was there planned support for this previously? https://github.com/jenkinsci/azure-keyvault-plugin/blob/master/src/main/java/org/jenkinsci/plugins/azurekeyvaultplugin/credentials/sshuserprivatekey/AzureSSHUserPrivateKeyCredentials.java#L51

**Comment by timja** [comment]
> Was there planned support for this previously?

no but that doesn't mean it can't be supported.

----

I understand what you're doing, although I don't hugely see the point when you have the key in key vault and you have the passphrase in the same key vault.

**Comment by CzapBran** [comment]
Our use case is entirely removing config as code credentials and relying on creds set from the AKV.  As of now in our JCasC, we set a private ssh key as:

``
- basicSSHUserPrivateKey:
                      description: "example"
                      id: "exampleSSHKey"
                      passphrase: "${passphraseFromKV}"
                      privateKeySource:
                        directEntry:
                          privateKey: "${privateKeyFromKV}"
                      scope: GLOBAL
                      username: "example"
``

We would like to remove this and depend solely on the AKV as the credential provider.  So while we could just fetch the SSH key and passphrase independently from the KV and use them within the pipeline, we would like to directly set the credential through tags:

``
az keyvault secret set --tags type=sshUserPrivateKey username=my-username \
  --vault-name my-vault \
  --name test-ssh \
  --passphrase-id passphraseID
  -f ~/.ssh/my-ssh-key
``

And then have the SSH cred be set in Jenkins for us.  Again, my direction could be incredibly off, if this is not recommended behaviour let me know

**Comment by CzapBran** [comment]
Actually, now that I'm on the topic of tags, there is one more feature I would like to implement.  Some credential provider plugins offer support to restrict credentials from showing up in Jenkins through a set property (example https://github.com/jenkinsci/kubernetes-credentials-provider-plugin/tree/master/docs#adding-credentials)

I would like to do the same with tags.  Since I'm already working in the `fetchCredentials()` method, it should be trivial to add support for a tag like `skipSecret=true` or something, it will block it from appearing in Jenkins.  Basically, if we are already setting the cred using tags, then there's really no need to have the direct secret appear in the KV.

This may be straying from the intended purpose of the plugin (It's not a direct credential provider), so let me know if you support this change

**Comment by timja** [comment]
sounds fine, maybe?

`jenkins-skip-secret`
