### ISSUE TITLE
Could not instantiate AzureKeyVaultBuildWrapper

### ISSUE THREAD

**Issue by milopz** [jenkinsci/azure-keyvault-plugin#183]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

1. Mount and AKS Cluster with Kubernetes 1.24.9 cluster
2. Mount Jenkins with versión 2.375.4 and create a job using a pod template like this one:
(Jenkins must have installed AzureKeyVault last version with its plugin dependencies).

podTemplate(yaml: '''
apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: mini
    image: eastus0acr0utils0general.azurecr.io/jenkins-worker:v4.0.11.15
    resources:
        limits:
            memory: 500Mi
            cpu: 0.5
        requests:
            memory: 500Mi
            cpu: 0.5
    command:
    - cat
    tty: true
    volumeMounts:
      - name: filesrba
        mountPath: /tmp/filesrba
  imagePullSecrets:
  - name: acr-credentials
  volumes:
    - name: filesrba
      azureFile:
            secretName: storage-credentials
            shareName: rba
            readOnly: false
'''
)

use this configuration to consume secrets en azure keyVault:

node(POD_LABEL) {
        wrap([$class: 'AzureKeyVaultBuildWrapper', azureKeyVaultSecrets: secrets, keyVaultURLOverride: 'https://eastus-kv-devops-abc.vault.azure.net/']) {
            wrap([$class: 'AzureKeyVaultBuildWrapper', azureKeyVaultSecrets: secrets_rebase, keyVaultURLOverride: 'https://eastus-kv-rebase-abc.vault.azure.net/']) {
                wrap([$class: 'AzureKeyVaultBuildWrapper', azureKeyVaultSecrets: secrets_db_rebase, keyVaultURLOverride: 'https://eastus-kv-tools-abc.vault.azure.net/']) {
                    plan = "${PLAN}"
                    devops_credentials = "${DEVOPS_CREDENTIALS}"
                    plan_credentials = "${PLAN_CREDENTIALS}"
                    db_rebase = "${DATABASE}"
                }
            }
        }

### Expected Results

I want mmy  job  finished successful integrating azure keyvault secrets

### Actual Results

JOb is having the error:

Caused: java.lang.IllegalArgumentException: Could not instantiate {delegate={$class=AzureKeyVaultBuildWrapper, azureKeyVaultSecrets=[{$class=AzureKeyVaultSecret, secretType=Secret, name=DEVOPSAUTOMATION, version=, envVariable=DEVOPS_CREDENTIALS}, {$class=AzureKeyVaultSecret, secretType=Secret, name=QACRED, version=, envVariable=PLAN_CREDENTIALS}], keyVaultURLOverride=[https://eastus-kv-devops-abc.vault.azure.net/}}](https://eastus-kv-devops-abc.vault.azure.net/%7D%7D) for org.jenkinsci.plugins.workflow.steps.CoreWrapperStep

**Comment by timja** [comment]
Please try with the documented syntax:
https://github.com/jenkinsci/azure-keyvault-plugin#scripted

**Comment by timja** [comment]
Closing as no response

**Comment by milopz** [comment]
Sorry for no response..

I review my configuration and follow the docuementation mentioned on https://plugins.jenkins.io/azure-keyvault/ bur I'm having the error still

I don'r know what could be the reason for this error.

**Comment by timja** [comment]
See: https://plugins.jenkins.io/azure-keyvault/#plugin-content-scripted

**Comment by milopz** [comment]
Finally i found the solution:

I have to change the sintax to this definition

node(POD_LABEL) {
        withAzureKeyvault(azureKeyVaultSecrets: [
            [envVariable: 'DEVOPS_CREDENTIALS', name: 'DEVOPSAUTOMATION', secretType: 'Secret'],
            [envVariable: 'PLAN_CREDENTIALS', name: params.PLAN_CREDENTIALS, secretType: 'Secret']
        ], 
        keyVaultURLOverride: 'https://eastus-kv-abc.vault.azure.net/') {
            withAzureKeyvault(azureKeyVaultSecrets: [
                [envVariable: 'PLAN', name: params.PRODUCT + '-' + params.CHANNEL, secretType: 'Secret']
            ], 
            keyVaultURLOverride: 'https://eastus-kv-def.vault.azure.net/') {
                withAzureKeyvault(azureKeyVaultSecrets: [
                    [envVariable: 'DATABASE', name: 'rebaseautomationdb', secretType: 'Secret'],
                ], 
                keyVaultURLOverride: 'https://eastus-kv-jkl.vault.azure.net/'){
                    plan = "${PLAN}"
                    devops_credentials = "${DEVOPS_CREDENTIALS}"
                    plan_credentials = "${PLAN_CREDENTIALS}"
                    db_rebase = "${DATABASE}"
                }
            }
        }
....code...
}
