### ISSUE TITLE
unable to authenticate to azure key vault using managed service identities

### ISSUE THREAD

**Issue by apeterson-dmigs** [jenkinsci/azure-keyvault-plugin#252]
hello,
i have been trying to connect my jenkins instance to one of my azure key vaults using a managed service identity. after entering the required key vault url and managed service identity credentials, i get a message saying that "manage service authentication is unavailable".  i am running my jenkins instance on localhost. the details of the error are given in the image below:

![Screenshot 2024-05-22 160820](https://github.com/jenkinsci/azure-keyvault-plugin/assets/170021418/e7cd9c45-f32d-4694-8777-b5de1a8f5de8)

**Comment by timja** [comment]
Are you running your Jenkins in Azure?

**Comment by timja** [comment]
Is the managed identity assigned to the Jenkins VM?

**Comment by apeterson-dmigs** [comment]
you're right, it isn't. that was the issue.

for future ref, make sure the UAMSI has access to the desired AKV and (if using an azure vm), make sure to assign the UAMSI to the VM with jenkins running on it. it will work even if the VM is in a different resource group to the UAMSI and AKV.
