### ISSUE TITLE
Use credential provider plugins

### ISSUE THREAD

**Issue by gavinfish** [jenkinsci/azure-keyvault-plugin#28]
### Your checklist for this issue

- [🙅‍♂] Jenkins version

- [🙅‍♂] Plugin version

- [🙅‍♂] OS

### Description

As described at [JCasC Handling Secrets](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#using-credential-provider-plugins), JCasC could use credential provider plugins to manage credentials and other sensitive information in the YAML configuration files.

It would be great to enable this feature for Azure users. Before I start this work, I want to find out what is the relationship between this plugin and [azure credentials plugin](https://github.com/jenkinsci/azure-credentials-plugin). They both cover the Key Vault service.

**Comment by gavinfish** [comment]
@timja Any ideas about this? And it would be great if you could give any suggestions about implementing credential provider for Azure. Thanks.

**Comment by timja** [comment]
This plugin allows retrieving credentials from azure key vault in a pipeline, 

It’s documented in the readme of azure credentials that you can get a secret from key vault but I was never able to find code or docs on how to do that

I would take a look at the AWS plugin for implementing the credential provider https://plugins.jenkins.io/aws-secrets-manager-credentials-provider

**Comment by gavinfish** [comment]
Some updates:

For the azure credentials plugin, it provides two different credential types for Jenkins: Key Vault Secret and Key Vault Certificate. They can be managed as other credentials in Jenkins.
![keyvault-secret](https://user-images.githubusercontent.com/6169722/72051009-658bd900-32fd-11ea-9ab9-62b2c6cdffa5.png)

For this plugin, it seems that it will directly get secret/certificate from Key Vault service.

From my point of view, it seems that this plugin is more like aws-secrets-manager-credentials-provider plugin. But there are some gaps:
1. This plugins depends on passwords/SP to authenticate with Azure, so there are still credentials exposed in JCasC. Managed identities for Azure resources(used to be MSI) may be an option here.

2. Extend the `CredentialsProvider` and `CredentialsStore` to manage own credentials store? This may not be necessary.

**Comment by timja** [comment]
> From my point of view, it seems that this plugin is more like aws-secrets-manager-credentials-provider plugin.

I see, the plugin was originally based on the hashicorp-vault-plugin to allow dynamically retrieving secrets from key vault. It's used extensively in pipelines.

> This plugins depends on passwords/SP to authenticate with Azure, so there are still credentials exposed in JCasC. Managed identities for Azure resources(used to be MSI) may be an option here.

The plugin also supports Managed identities as well

> Extend the CredentialsProvider and CredentialsStore to manage own credentials store? This may not be necessary.

I think it would be a good option to explore so that all secrets can be transparently managed in key vault, note I don't have any experience with this and don't know how that works with more complex credentials

The other option would be to implement the JCasC SecretSource extension point: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#secret-sources

**Comment by myhau** [comment]
+1
