### ISSUE TITLE
Option to disable credential provider cache

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-keyvault-plugin#39]
https://github.com/jenkinsci/azure-keyvault-plugin/pull/33 introduces an in-memory cache for credentials, some users may not want this, would be good to have a property / configuration item to disable this.

**Comment by timja** [comment]
cc @gavinfish

**Comment by timja** [comment]
probably not needed as we just cache the ids

**Comment by gavinfish** [comment]
Agree @timja
