### ISSUE TITLE
CredentialProvider: Non string credential support

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-keyvault-plugin#44]
### Description

aws-secrets-manager-credentials-provider supports this by encoding additional information in 'tags' we can possibly do similar with the Content-Type field.

https://github.com/jenkinsci/aws-secrets-manager-credentials-provider-plugin/blob/master/docs/README.md#username-with-password

**Comment by timja** [comment]
cc @gavinfish 
also ref: https://github.com/jenkinsci/azure-keyvault-plugin/issues/42#issuecomment-597773138

**Comment by mastercard-rob** [comment]
I've just released this plugin, it might help, supports UsernamePassword, SSHUserPrivateKey and PersonalAccessToken (Gitlab) credentials which are stored as secrets in Azure Keyvault

https://plugins.jenkins.io/azure-credentials-ext/

**Comment by timja** [comment]
Interesting

**Comment by ilons** [comment]
I just hit this as well.
Any plans to implement this using tags?
For example, if one named `username` are found it could take its value as username treat the secret as password?

**Comment by timja** [comment]
Any contributions are welcomed :)

**Comment by ilons** [comment]
> Any contributions are welcomed :)

Yeah, I started to have a look at it, haven't written java in ~15 years, and no experience of Jenkins plugin development tho :-)

**Comment by timja** [comment]
there's a bit of a getting started guide here: https://github.com/jenkinsci/.github/blob/master/CONTRIBUTING.md
