### ISSUE TITLE
Cannot change Credential ID having insufficient rights in Configure system

### ISSUE THREAD

**Issue by jaheikki** [jenkinsci/azure-keyvault-plugin#47]
### Your checklist for this issue

- [ x] Jenkins version
2.190.1
- [x ] Plugin version
1.7
- [ x] OS
Linux

### Description
When configuring Azure Key Vault Plugin in Jenkins UI (in Configure system) you need to set 2 things, the 'Key Vault URL' and 'Credential ID'.  I set the URL first and then from the drop down menu I chose service principal as new Credential ID. However the Credential ID did not have proper rights in Azure key vault and this caused Exception to occur in Configure page: "Keyvault error exception - Status Code 403 - Access denied - Caller was not found on any access policy". This is maybe correct reason for not able to use the vault...but in the meanwhile you are middle of configuring vault, the other Jenkins users cannot run any builds: "java.lang.IllegalArgumentException: Must provide a replacement value for each pattern". 

I found out that I do not want to use the service principal concerning so I created new one with correct keyvault rights. However it is not possible to change the credential anymore from the drop down menu!
So to correct the problem (which is total non-usability of Jenkins) I tried to remove the plugin. After reinstalling plugin the same 'non-working' service principal was shown in UI in Credential ID field and using the drop down menu was not possible (the configuration remains in disk due to plugin uninstall did not delete the configuration from disk). Only way to solve the problem was to add correct access rights in keyvault for the service principal. Of course if you know the location of plugin configuration you may be able to clean that config, but how may of us normal users know that...

This is truly annoying feature because you first get Jenkins web UI full of "exception figures" and the jenkins in non-usable that time. There must be way to clear the configuration from UI, to be able to re-configure the Credential ID (you should be able change the Credential ID from the dropdown menu even if previous selection (service principal) did not have enough rights).

**Comment by timja** [comment]
Do you have any screenshots? was the box disabled or was there an error?

**Comment by jaheikki** [comment]
Yes I have.

![image](https://user-images.githubusercontent.com/8567508/76615280-63770e00-652a-11ea-9a69-76bdf7556594.png)

**Comment by jaheikki** [comment]
And the UI is full of those 'Oops Stack trace'...

**Comment by timja** [comment]
I'll take a look, thanks for the report

**Comment by timja** [comment]
There's a proposed fix: https://github.com/jenkinsci/azure-keyvault-plugin/pull/48

In the meantime you can disable the credential provider via:
Manage Jenkins => Credentials

And update it so that the Azure KeyVault credential provider isn't active anymore
