### ISSUE TITLE
No Secret in KeyVault should return null

### ISSUE THREAD

**Issue by wuerzelchen** [jenkinsci/azure-keyvault-plugin#59]
### Problem
I have a pipeline which needs to check for a certain secret in my Keyvault. The pipeline cannot be sure if the Secret is there, or not.
In the case that the secret is not existing, the pipeline breaks with an exception.

### Expectation
As the pipeline, I want to get all the secrets I define as params. If there is no such a secret, I expect to get a null kind of value as a result, so I can act on that inside of the pipeline

Any tips on how to get a working solution are welcome, too. Putting this whole thing in a try/catch block didn't work for me since I do have multiple unknown variables, which might be set, or not.

### Reference to code parts:
[kv buid wrapper](https://github.com/jenkinsci/azure-keyvault-plugin/blob/1bf521fe6598eb4600a7d4c99e6023e184cb1af9/src/main/java/org/jenkinsci/plugins/azurekeyvaultplugin/AzureKeyVaultBuildWrapper.java#L243)
[kv step](https://github.com/jenkinsci/azure-keyvault-plugin/blob/1bf521fe6598eb4600a7d4c99e6023e184cb1af9/src/main/java/org/jenkinsci/plugins/azurekeyvaultplugin/AzureKeyVaultStep.java#L162)

**Comment by timja** [comment]
Not supported currently, you would need to add some sort of failOnError support here like some other steps have and set it to false

Or separate loading of your secrets out that you aren’t sure about to individual steps and try catch those

**Comment by wuerzelchen** [comment]
Thanks for your quick response. I'll see what I can do.
