### ISSUE TITLE
Inconsistent capitalisation between scripted and declarative syntax

### ISSUE THREAD

**Issue by silvester747** [jenkinsci/azure-keyvault-plugin#61]
### Your checklist for this issue

- [x] Jenkins version: 2.222.3

- [x] Plugin version: 1.0.0

- [x] OS: Linux

### Description

There is a very subtle difference between the names used for scripted and declarative syntax:
Scripted: `withAzureKeyvault`
Declarative: `azureKeyVault`

Notice the `v` vs `V`. This may confuse more people than me :-).

Probably the syntax for scripted pipelines should be `withAzureKeyVault`

**Comment by timja** [comment]
Oops

**Comment by timja** [comment]
Currently not planned, Jenkins does not have a way to rename steps or alias them, you would either need to have the two steps present or delete the old one breaking a number of pipelines.

You also can't hide the existing step other than moving it to the Advanced/Deprecated section.

If someone feels strongly then we can do this but not a great UX, given only one person has mentioned it in 2 years closing as not planned.
