### ISSUE TITLE
Service principal credentials verify is not working

### ISSUE THREAD

**Issue by phanitejanunna** [jenkinsci/azure-keyvault-plugin#63]
### Your checklist for this issue

- [ ] Jenkins version 2.249.1

- [ ] Plugin version 2.0

- [ ] OS "Debian GNU/Linux

### Description

Please describe your issue here.
I am working on integrating jenkins with Azure Keyvault for which I am following the blog: https://www.jenkins.io/blog/2020/03/30/azure-key-vault-cred-provider/

I have configured the service principal as a Jenkins credential and when I click on verify service principal I get an error "The provided credentials are not valid". Jenkins logs doesn't show any other information except "2020-09-24 13:50:40.548+0000 [id=414409]	INFO	c.m.a.a.AuthenticationAuthority#doInstanceDiscovery: [Correlation ID: 3b2f6feb-e964-4603-86cc-6fa3b0b6e604] Instance discovery was successful"

However, when I try to fetch a token using postman with the same service principal, there is no issue. So, I am sure that the service principal credentials are correct. 

Could you please help me to fix this issue? Thanks in advance.

**Comment by timja** [comment]
I've just tested it and it works for me.

Can you screenshot your credential page? black out whatever you aren't comfortable sharing but I need to see the fields that are filled in at least.

FTR the service principal credential comes from the Azure Credentials plugin.

**Comment by phanitejanunna** [comment]
Here is the screenshot. Just FYI, Jenkins is running behind corporate proxy and the following urls are whitelisted:

- login.microsoftonline.com
- ourkeyvault.vault.azure.net

![Capture](https://user-images.githubusercontent.com/59478957/94162261-d02e7600-fe86-11ea-9eb0-711bc95f0b9b.PNG)

**Comment by timja** [comment]
Omg -.-
https://github.com/jenkinsci/azure-credentials-plugin/blob/038abb0da67de3b148daa2f3fd87085f128f6f80/src/main/java/com/microsoft/azure/util/AzureCredentials.java#L430-L432

the plugin doesn't log the reason for failure -.-

https://github.com/jenkinsci/azure-credentials-plugin/pull/47

you could try that build of the azure credentials plugin to see if it helps ^^

more debug could be added, i.e. the whole exception but that's a slightly bigger change, can be done if required though

**Comment by phanitejanunna** [comment]
@timja Thank you for looking the issue. While exception handling is take care of, could you please let me know whether any other URLs need to be whitelisted at our proxy level?

**Comment by timja** [comment]
I have no idea, I don't block them.

**Comment by phanitejanunna** [comment]
Ok. Where can I find the plugin(hpi file) containing your fix for me to test?

**Comment by timja** [comment]
https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fazure-credentials-plugin/detail/PR-47/1/artifacts

**Comment by phanitejanunna** [comment]
Thank you for the link. I see an error message now. "The provided credentials are not valid: java.io.IOException: Failed to authenticate with proxy". I am wondering which url gives this exception because the following urls have already been whitelisted.

- login.microsoftonline.com
- ourkeyvault.vault.azure.net

**Comment by timja** [comment]
Do you have to authenticate with your proxy?

**Comment by phanitejanunna** [comment]
Proxy authentication has been disabled for the above two urls. I assume azure credentials plugin tries to reach out to a different url which hasn't been whitelisted. Do you have the list of URLs which the plugin calls?

**Comment by timja** [comment]
If you click advanced on the credential a number of fields will pop out. If you click the help icon next to each it will tell you the endpoints

**Comment by phanitejanunna** [comment]
Thank you for your suggestion. Now all the URLs have been whitelisted. However, I receive an error "The subscription id is not valid" even though the subscription is valid. There are few others who have reported a similar issue. Any idea about how to fix this? 

Ref: https://stackoverflow.com/questions/48899184/error-while-adding-azure-credentials-on-jenkins

**Comment by timja** [comment]
What RBAC permissions does your SP have?
I’m away from computer today but I can check the code next week if you don’t figure it out.

**Comment by timja** [comment]
I think it needs at least subscription read to pass that check, even if you don’t need that to retrieve the secret from the vault

**Comment by phanitejanunna** [comment]
@timja Did you have time to check this? Are you sure that the SP needs read permission on the entire subscription?

**Comment by timja** [comment]
It doesn’t need it to work, but yes to verify it needs read to the subscription

**Comment by phanitejanunna** [comment]
@timja Our Jenkins is running behind a proxy. So, I have set the HTTP_PROXY and HTTPS_PROXY as environment variables in my pipeline. This is my pipeline: 

pipeline {
  agent any
  environment {
    HTTP_PROXY = "http://proxy:port"
    HTTPS_PROXY = "http://proxy:port""
    NO_PROXY = "set"
  }
  stages {
    stage('SECRET') {
      options {
      azureKeyVault([[envVariable: 'KV_SECRET', name: 'kvsecret', secretType: 'Secret']])
      }
      steps{
          sh 'echo $KV_SECRET'
      }
    }
  }
}

However, we get a time out an exception when connecting we execute this pipeline. I am sure that the key vault URL is whitelisted at the proxy level. Does the plugin support proxy?

io.netty.channel.ConnectTimeoutException: connection timed out: abc.vault.azure.net/xx.xx.xxx.xxx:443
  at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:563)
Also:   java.lang.Exception: #block terminated with an error
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
    at reactor.core.publisher.Mono.block(Mono.java:1663)
    at com.azure.security.keyvault.secrets.SecretClient.getSecretWithResponse(SecretClient.java:171)
    at com.azure.security.keyvault.secrets.SecretClient.getSecret(SecretClient.java:150)
    at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultCredentialRetriever.getSecretBundle(AzureKeyVaultCredentialRetriever.java:101)
    at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultStep$ExecutionImpl.getSecret(AzureKeyVaultStep.java:145)
    at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultStep$ExecutionImpl.getSecretsMap(AzureKeyVaultStep.java:158)
    at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultStep$ExecutionImpl.start(AzureKeyVaultStep.java:131)

**Comment by timja** [comment]
not sure.

**Comment by phanitejanunna** [comment]
@timja Thank you for the reply. Is it possible to test from your side and let me know?

**Comment by phanitejanunna** [comment]
@timja Could you please let us know whether the plugin supports proxy?

**Comment by timja** [comment]
I don't know, it's not something I have access to test with.

Proxy support is always best effort, and mostly contributed by developers who are blocked because of proxies...

**Comment by luka5** [comment]
I found this ticket yesterday searching for proxy support in this `azure-keyvault` plugin. So for the record: the plugin uses the Proxy settings configured inside Jenkins to access the Azure Keyvault, if the `azure-credentials` plugin is installed in version `180.vd0decee98185` or newer.

@timja  I tried to update the dependency of this plugin, but failed with `Rule 5: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:`. I'm not sure how to resolve that

**Comment by timja** [comment]
Don't worry about updating the dependency, Jenkins will use the newer version at runtime if you upgrade through the plugin center.

It will be updated in https://github.com/jenkinsci/azure-keyvault-plugin/pull/79 soon

So is this issue solved?

**Comment by luka5** [comment]
As far as I understood the root cause: yes
