### ISSUE TITLE
How to specify which managed identity to use

### ISSUE THREAD

**Issue by fvztdk** [jenkinsci/azure-keyvault-plugin#67]
### Your checklist for this issue

- [x] Jenkins version 2.263.1

- [x] Plugin version 2.1

- [x] OS Linux

### Description

Hi,

I created a managed identity with permissions to access my keyvault, the problem is I don't see how to configure the plugin to use this specific managed identity

**Comment by timja** [comment]
It currently only works if there’s one identity assigned, that’s a limitation in the azure-credentials plugin which we are consuming here

Do you have a use case where your Jenkins controller needs more than one identity assigned?

**Comment by fvztdk** [comment]
And how can  I configure which identity the azure-credentials should use (I know, different plugin, just if you have the knowledge)?

My use case is that I have multiple jenkins deployed in a kubernetes cluster, each one of those jenkins have their keyvault that should be accessible only by that jenkins. I can create for each jenkins their corresponding managed identity, but I need to configure the plugin to use a specific managed identity.

**Comment by timja** [comment]
Are you using aad-pod-identity? If so you just need to only bind the specific identity to the pod and aad-pod-identity will only expose the assigned identity to the pod

**Comment by fvztdk** [comment]
No I'm not, will take a look into that, thanks
