### ISSUE TITLE
Disable Azure Key Vault Credentials Provider (Beta)

### ISSUE THREAD

**Issue by stawii** [jenkinsci/azure-keyvault-plugin#72]
Even when I have no global configuration for this plugin and I'm only using `azureKeyVault()` or `withAzureKeyvault()` with overrides in each job, it still populates global credentials in Jenkins making them available for all other jobs which might be a security issue. Also it "spams in" all secrets found in Azure KeyVault, even if they weren't used in any place.

**Comment by timja** [comment]
You can disable it in the 'Configure Credential Providers' view from the system configuration

**Comment by stawii** [comment]
Woah! That was fast and precise answer! Thanks!

**Comment by myahl-uncomn** [comment]
How can this be done via CasC?

**Comment by timja** [comment]
should be supported, please configure it manually locally and then export the configuration.

**Comment by myahl-uncomn** [comment]
I did that, but there's no difference from exporting the configuration before setting it manually.

**Comment by timja** [comment]
I'll check later on
