### ISSUE TITLE
JCasC Exporting credentials as encrypted text shows "****"

### ISSUE THREAD

**Issue by Dokki-767** [jenkinsci/azure-keyvault-plugin#85]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.289.3
OS: Windows Server 2019 - 10.0
---
ace-editor:1.1
ansicolor:1.0.0
apache-httpcomponents-client-4-api:4.5.13-1.0
azure-ad:178.v7b93892fbe4c
azure-credentials:182.v3ccd4a755864
azure-keyvault:123.v1aba71c2d365
azure-sdk:30.vf3165534d6e8
blueocean-commons:1.24.8
blueocean-rest:1.24.8
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.0-1
bouncycastle-api:2.21
branch-api:2.6.5
build-user-vars-plugin:1.7
caffeine-api:2.9.1-23.v51c4e2c879c8
checks-api:1.7.2
cloudbees-folder:6.16
command-launcher:1.6
configuration-as-code:1.51
copyartifact:1.46.1
credentials-binding:1.27
credentials:2.5
dark-theme:0.0.12
display-url-api:2.3.5
durable-task:1.39
echarts-api:5.1.2-9
font-awesome-api:5.15.3-4
git-client:3.9.0
git-server:1.10
git:4.8.1
handlebars:3.0.8
jackson2-api:2.12.4
jdk-tool:1.5
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.52
lockable-resources:2.11
login-theme:1.1
mailer:1.34
matrix-auth:2.6.8
matrix-project:1.19
momentjs:1.1.1
pipeline-build-step:2.15
pipeline-graph-analysis:1.11
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.1
pipeline-model-definition:1.9.1
pipeline-model-extensions:1.9.1
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.9.1
pipeline-stage-view:2.19
pipeline-utility-steps:2.8.0
plain-credentials:1.7
plugin-util-api:2.4.0
popper-api:1.16.1-2
popper2-api:2.9.3-1
powershell:1.5
resource-disposer:0.16
saml:2.0.7
scm-api:2.6.5
script-security:1.78
simple-theme-plugin:0.7
snakeyaml-api:1.29.1
ssh-credentials:1.19
sshd:3.1.0
structs:1.23
theme-manager:0.6
timestamper:1.13
trilead-api:1.0.13
windows-azure-storage:359.v09573e5ff73f
workflow-aggregator:2.6
workflow-api:2.46
workflow-basic-steps:2.23
workflow-cps-global-lib:2.21
workflow-cps:2.93
workflow-durable-task-step:2.39
workflow-job:2.41
workflow-multibranch:2.26
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8
ws-cleanup:0.39
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Windows Server 2019
no agents involved
```

### Reproduction steps

Trying to export configured Azure Service Principal credentials that are used for Key Vault integration as encrypted text, JSasC 'view configuration' is not exporting the clientSecret properly.  JSasC export shows "****" instead of encrypted value that can be stored in JCasC configuration YAML.

### Results

Expected result:

Encrypted text of secret/password

Actual result:

Literally "****"

**Comment by timja** [comment]
That's a bug in the azure-credentials plugin,

https://github.com/jenkinsci/azure-credentials-plugin/blob/master/src/main/java/com/microsoft/azure/util/AzureCredentials.java#L543

Returns a String instead of a secret, jcasc is making it so it doesn't show in plain text.

Given it would be a breaking change to azure-credentials I think it's unlikely to be fixed given the low impact of this?

(not related to jcasc as such so closing, feel free to continue the discussion though if you've got more to add)

**Comment by Dokki-767** [comment]
Thanks, I wasn't sure which plugin this was attributed too.  I can open a bug with the Azure Credentials but if it's a breaking change and not likely to be fixed, that could be problematic for my setup.  I'm not super versed in the alternate methods of storing/injecting credentials into JCasC outside of encrypted value.

**Comment by timja** [comment]
Lots of options here https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc
