### ISSUE TITLE
Support using ssh private keys

### ISSUE THREAD

**Issue by SirNeo** [jenkinsci/azure-keyvault-plugin#88]
### Feature Request

It will be interesting if the library would be able to support "SSHUserPrivateKey".  I would like to store SSH Private Keys in Azure Key Vault and so retrieve them to execute remote command using ssh.

Currently using Credentials:

    withCredentials([sshUserPrivateKey(credentialsId: "my_credential", keyFileVariable: "my_ssh_key", usernameVariable: "my_username")]) {
        remote.host = "x.x.x.x"
        remote.user = "${my_username}"
        remote.identityFile = "${my_ssh_key}"

       sshCommand remote: remote, command: "ls -la"
     }

Feature Requested:

    def secrets = [
        [ secretType: 'Secret', name: 'my_username', envVariable: 'my_username' ],
        [ secretType: 'Secret', name: 'my_ssh_key', envVariable: 'my_ssh_key' ]
    ]

    withAzureKeyvault(secrets) {
        remote.host = "x.x.x.x"
        remote.user = "${my_username}"
        remote.identityFile = "${my_ssh_key}"

       sshCommand remote: remote, command: "ls -la"
    }

**Comment by timja** [comment]
```
    withCredentials([string(credentialsId: 'ssh-key', variable: 'SSH_KEY')]) {
        sh '''
          echo $SSH_KEY > my-key
        '''
    }
```
