### ISSUE TITLE
Disable credential provider via casc

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-keyvault-plugin#92]
How can this be done via CasC?

_Originally posted by @myahl-uncomn in https://github.com/jenkinsci/azure-keyvault-plugin/issues/72#issuecomment-930307787_

**Comment by myahl-uncomn** [comment]
Thanks!

**Comment by timja** [comment]
@myahl-uncomn 

It works after these PRs:

https://github.com/jenkinsci/configuration-as-code-plugin/pull/1752
https://github.com/jenkinsci/credentials-plugin/pull/235
